[package]
name = "blastcube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.63"
enum-iterator = "1.2.0"
smallvec = "1.9.0"
